### ISSUE TITLE
Darkmode wird erst aktiv, wenn der Spacestatus geladen ist

### ISSUE THREAD

**Issue by MG-5** [netz39/www.netz39.de#102]

**Comment by MG-5** [comment]
Möglichweise liegt hier ein Problem mit Wittgenstein vor. Immer wenn die Seite eine längere Zeit nicht geladen wurde, braucht der Space-Status mehrere Sekunden zum Laden.
Wurde die Seite vor Kurzem geladen, wird der Spacestatus (trotz deaktiviertem Cache) sehr schnell geladen.

Wenn ich mich richtig erinnere, hatte die alte Webseite und das Wiki das Problem auch.

Aufruf, nachdem die Webseite längere Zeit nicht geladen wird.
![Snapshot_2024-04-03_16-36-59](https://github.com/netz39/www.netz39.de/assets/12341832/4f98e112-ddd2-4fc3-8833-6bdce2cf23c6)

----

Aufruf, nachdem die Webseite vor kurzer Zeit bereits geladen wurde und quasi den Space-API "geweckt" hat. (Cache ist deaktiviert.)
![Snapshot_2024-04-03_16-43-34](https://github.com/netz39/www.netz39.de/assets/12341832/4d5c2775-bb19-4b6a-a75a-c795bdc257c5)

**Comment by penguineer** [comment]
Das Problem ist hier, dass eine externe Ressource synchron geladen wird. Folgendes könnte man prüfen:
* Das Bild per JavaScript asynchron laden.
* Das Theme kommt über ein Script zustande. Wird das eventuell deferred geladen?

**Comment by penguineer** [comment]
Ich habe  keinen  der Aspekte der Seite gestaltet, deshalb weiß ich nicht, weshalb  ich zugeordnet wurde.

**Comment by penguineer** [comment]
> Möglichweise liegt hier ein Problem mit Wittgenstein vor. Immer wenn die Seite eine längere Zeit nicht geladen wurde, braucht der Space-Status mehrere Sekunden zum Laden. 

Wittgenstein ist ein Raspberry Pi A hinter einer "Dial-Up"-Verbindung. Hier darf in keinem Fall eine schnelle Antwort erwartet werden. Wenn  das Ladeverhalten zeitkritisch ist, muss es asynchron gestaltet werden.

**Comment by MG-5** [comment]
Ich habe gehofft, dass das Problem mit dem Langsam-Laden schneller behoben ist als die Webseite an sich anzufassen. Deshalb habe ich dich als derjenige, der für Wittgenstein zuständig ist, zugewiesen.

Gut, dann müssen wir mal schauen, wie wir das Laden des Skriptes für den Darkmode und das Laden des Bildes getrennt kriegen. Dafür sind meine Kenntnisse in JS leider zu rudimentär.

**Comment by penguineer** [comment]
> Ich habe gehofft, dass das Problem mit dem Langsam-Laden schneller behoben ist - als die Webseite an sich umzubauen. Deshalb habe ich dich als denjenigen, der für Wittgenstein zuständig ist, zugewiesen.

Aufgrund der Art, wie das eingebunden ist, wir das langsame Laden nie behoben werden können.

**Comment by MG-5** [comment]
> Aufgrund der Art, wie das eingebunden ist, wir das langsame Laden nie behoben werden können.

Woran liegt das? Frage ich jetzt aus technischem Interesse

**Comment by penguineer** [comment]
> > Aufgrund der Art, wie das eingebunden ist, wir das langsame Laden nie behoben werden können.
> 
> Woran liegt das? Frage ich jetzt aus technischem Interesse

Wie oben geschrieben: Systeme sind nicht die schnellsten und unsere Internetanbindung ist nicht dafür gemacht, schnell Inhalte auszuliefern.

Rein vom Design her ist es sowieso eine schlechte Idee, externe Ressourcen synchron zu laden, wenn Timing wichtig ist.

**Comment by MG-5** [comment]
Naja es ist ja für die nächsten 10-20 min sofort erreichbar, sofern die Webseite einmal komplett geladen ist. Nach einer halben Stunde haste wieder die 10sek, die er für das Bild laden braucht. Es geht also nicht per-se um Schnelligkeit eines Systems.

**Comment by penguineer** [comment]
Nein, es geht vielleicht auch um die Frage, welche Routen gesetzt sind, ob intern vllt ARP-Caches geleert werden, ...

**Comment by MG-5** [comment]
Fixed by #128
