### ISSUE TITLE
Kalender: Startzeit wird nicht angezeigt, wenn die Endzeit fehlt

### ISSUE THREAD

**Issue by MG-5** [netz39/www.netz39.de#117]
Bei den Stammtischen wird im Kalender (nicht in der Eventbeschreibung selbst) keine Startzeit angezeigt. Wahrscheinlich liegt es daran, dass in der md-Datei die end_time fehlt. Vielleicht reicht es, diesen defaultmäßig auf denselben Startwert setzen?

**Comment by teuserer** [comment]
Dieses Verhalten ist im README.md dokumentiert. Grund ist, dass Events mit Startzeit auf der Webseite nicht so schön aussehen.
![Screenshot_20240327-080226_Fennec](https://github.com/netz39/www.netz39.de/assets/151996707/fbb5b8fa-daae-4695-b213-b6217594d04d)

**Comment by MG-5** [comment]
Ah okay, das ist natürlich ein gutes Argument. Solange es in dem eigenen Kalender richtig mit dem Zeitslot dargestellt wird, passt das ja soweit :D
