### ISSUE TITLE
Kalender: Vergangene Events herausfiltern bei Abonnement

### ISSUE THREAD

**Issue by MG-5** [netz39/www.netz39.de#124]
Wenn man  die ICS abonniert, werden vergangene Events auch mitangezeigt.
Das heißt, die generierte Datei wird jedes Mal größer.

Vorher wurde bei der Lösung mit Jeykll-template, die Events vorm Zeitpunkt des Deploys herausgefiltert.

**Comment by teuserer** [comment]
Ich würde vorschlagen, dass events der 356 Tage vor dem Deploy noch mitgenommen werden. Dann kann man sie noch eine Weile länger im eigenen Kalender sehen.

**Comment by MG-5** [comment]
Jo, das ist eine gute Idee :)
