### ISSUE TITLE
Weiterleitung vom alten Kalenderfeed

### ISSUE THREAD

**Issue by LeSpocky** [netz39/www.netz39.de#30]
Den Kalender im WordPress konnte man als iCal Feed abonnieren unter folgender URL:

https://www.netz39.de/feed/eo-events/

Von dort sollte es ggf. eine Weiterleitung (HTTP Status 301 oder 302) auf den neuen Feed geben.

**Comment by 24367dfa** [comment]
https://github.com/sustainers/website/issues/275

Allgemein können wir uns nicht ein bisschen Gedanken machen, was wir mit dem Kalender noch anfangen wollen. ICal Feed wäre glaube ich super.

**Comment by 24367dfa** [comment]
> Den Kalender im WordPress konnte man als iCal Feed abonnieren unter folgender URL:
> 
> https://www.netz39.de/feed/eo-events/
> 
> Von dort sollte es ggf. eine Weiterleitung (HTTP Status 301 oder 302) auf den neuen Feed geben.

Ich glaube, derzeit haben wir keinen Feed, sondern nur die Kalenderseite www.netz39.de/events

**Comment by MG-5** [comment]
Da kriegt man schon was gebastelt

https://rentalbookingsoftware.com/adding-icalendar-or-ics-export-to-fullcalendar/

**Comment by LeSpocky** [comment]
> Siehe PR #45 

Das wäre ics. Das braucht eine stabile URL und  die Weiterleitung muss dann dazu kommen.

**Comment by penguineer** [comment]
Wir haben keine Kontrolle über den HTTP-Server. Eine "Weiterleitung" wäre am ehesten ein Ausliefern des Feeds auf der ursprünglichen URL (ggf. als Kopie).

**Comment by LeSpocky** [comment]
Die Kontrolle haben wir aber nur nicht, weil wir GitHub das ausliefern lassen, richtig?

**Comment by 24367dfa** [comment]
> Wir haben keine Kontrolle über den HTTP-Server. Eine "Weiterleitung" wäre am ehesten ein Ausliefern des Feeds auf der ursprünglichen URL (ggf. als Kopie).

redirects gehen schon. so haben wir zB den Wiki Link realisiert.

Ich würde aber gern einmal die Frage stellen, ob wir wissen, wie viele Leute den alten Feed abboniert hatten... wenn wir uns den Aufwand jetzt für 2 Personen machen, die vielleicht auch noch alle hier mitlesen, würde ich das eventuell eher beiseite legen.

**Comment by LeSpocky** [comment]
Am Sat, Nov 04, 2023 at 12:12:14AM -0700 schrieb David:
> > Wir haben keine Kontrolle über den HTTP-Server. Eine "Weiterleitung" wäre am ehesten ein Ausliefern des Feeds auf der ursprünglichen URL (ggf. als Kopie).
> 
> redirects gehen schon. so haben wir zB den Wiki Link realisiert.

Gut zu wissen!

> Ich würde aber gern einmal die Frage stellen, ob wir wissen, wie viele Leute den alten Feed abboniert hatten... wenn wir uns den Aufwand jetzt für 2 Personen machen, die vielleicht auch noch alle hier mitlesen, würde ich das eventuell eher beiseite legen.

Das war ein öffentlich einsehbarer Link auf unserer Website.  Wir
haben praktisch keine Möglichkeit das rauszufinden.  Das können zwei
Leute gewesen sein oder zwanzig oder zweihundert. :man_shrugging:

**Comment by 24367dfa** [comment]
ich hab mal einen Konkurrenzvorschlag in #67 gemacht. Ich denke, dass wir da simpler zum Ziel gelangen und ganz ohne das Ausliefern zusätzlichen JavaScript Codes auskommen.

**Comment by penguineer** [comment]
> Die Kontrolle haben wir aber nur nicht, weil wir GitHub das ausliefern lassen, richtig?

Genau.

Wobei ich das GitHub-Hosting für solche Webseiten insgesamt schon praktisch finde, weil wir uns um die ganzen Themen Schutz, DDoS, Skalierung halt nicht kümmern müssen. Ist jetzt kein riesiges Thema, aber es ist inzwischen auch so leicht, Seiten mit auf die Angriffsliste zu setzen, dass ich nicht böse bin, wenn wir das Thema nicht haben.

Insbesondere weil das Netz39 ja auch kein Incidence-Response-Team hat. ;)
