### ISSUE TITLE
"Edit page on GitHub" link broken

### ISSUE THREAD

**Issue by JensWinter** [netz39/www.netz39.de#48]
Beim Klick auf den Link "Edit page on GitHub" im Fuß erscheint diese Anzeige:

![image](https://github.com/netz39/www.netz39.de/assets/6548550/e50fde3a-8e2d-42f2-993f-b870d3fc36bb)

**Comment by MG-5** [comment]
Damn, das war eine Änderung heute Nacht, von der ich dachte, dass sie ein anderes Problem beheben würde, was sie aber nicht tat.
Dann reverte ich mal die Änderung.
