### ISSUE TITLE
Mastodon-Link anpassen, damit er als Verifikation funktioniert

### ISSUE THREAD

**Issue by t-aus-m** [netz39/www.netz39.de#61]
Wie [hier](https://joinmastodon.org/verification) dokumentiert, können Links mit Backlinks von Webseiten als Verifikation in Mastodon verwendet werden, solange das `rel="me"`-Tag gesetzt ist. Es wäre cool, das auf der Website so anzupassen, dass der Link als Verification funktioniert.

**Comment by MG-5** [comment]
Habe ein PR eingereicht. Schau mal, ob das so Sinn ergibt

**Comment by t-aus-m** [comment]
Das scheint doch nicht geklappt zu haben :see_no_evil:

**Comment by MG-5** [comment]
Woran sehe ich denn, dass es funktioniert?

**Comment by t-aus-m** [comment]
Meines Verständnisses nach müsste jetzt im HTML beim Mastodon-Link der `rel="me"` gesetzt sein. Bei mir im Browser sieht es so aus:
![grafik](https://github.com/netz39/www.netz39.de/assets/12219297/4e0f65a7-51dc-4845-90e6-1ea8c612c38d)

**Comment by LeSpocky** [comment]
> Woran sehe ich denn, dass es funktioniert? 

Auf dem Profil https://machteburch.social/@netz39 ist beim Link zu unserer Website ein Haken oder der ist grün hinterlegt o.ä.

**Comment by MG-5** [comment]
So, PR #64 ist jetzt offen, das sollte jetzt auf jeden Fall funktionieren, habe ich in meinem Firefox getestet :D

**Comment by MG-5** [comment]
@LeSpocky du kannst auch gerne den PR approven...

**Comment by LeSpocky** [comment]
> @LeSpocky du kannst auch gerne den PR approven... 

Ich sehe zwar den Change, aber ich kenne mich mit dem System dahinter gar nicht aus und kann daher nicht bewerten ob das korrekt ist oder nicht.
