### ISSUE TITLE
Repo umbenennen in www.netz39.de

### ISSUE THREAD

**Issue by 24367dfa** [netz39/www.netz39.de#7]
@LeSpocky @MG-5 @penguineer gibts dazu Meinungen, Widerspruch, Hinweise? Sonst würde ich das heute abend mal angehen.

**Comment by LeSpocky** [comment]
Mir ist das relativ egal, _wie_ das Repo heißt.  Wichtiger wäre mir, _wo_ es liegt.  Siehe dazu [#907: Backup bzw. Mirror der Homepage anlegen](https://redmine.n39.eu/issues/907) in unserem eigenen Bugtracker.

**Comment by 24367dfa** [comment]
Ja, David will ich das lfs Thema fertig haben.

**Comment by LeSpocky** [comment]
> Ja, davor will ich das lfs Thema fertig haben.

Ja, gute Idee.
