### ISSUE TITLE
Tools Ordner in Header-Bar

### ISSUE THREAD

**Issue by timherrm** [netz39/www.netz39.de#76]
![grafik](https://github.com/netz39/www.netz39.de/assets/23706249/d388af2e-e831-44ed-8bd7-18f39564b71c)

Wieso wird der da angezeigt und was kann man dagegen tun? :D

**Comment by 24367dfa** [comment]
Ich denke, wir können den Pfad /Tools irgendwo in der Jekyll cinfig als ignore eintragen.
