### ISSUE TITLE
Spenden im Impressum anpassen

### ISSUE THREAD

**Issue by timherrm** [netz39/www.netz39.de#85]
Da wir jetzt auch eine dedizierte Spendenseite haben kann ja aus dem Impressung darauf gelinkt werden? Oder den Text da auch nochmal mit hinkopieren? "Die Kontoverbindung gibt es auf Anfrage." kann da jedenfalls raus.

**Comment by MG-5** [comment]
Eigentlich kann das Kapitel ja komplett raus... Wenn nicht, reicht eine Verlinkung
