### ISSUE TITLE
git LFS Quota überschreitet regelmäßig unser freies Kontingent

### ISSUE THREAD

**Issue by 24367dfa** [netz39/www.netz39.de#99]

**Comment by 24367dfa** [comment]
LFS Bandwidth Quota ist 1GB im Free Tier
1 datapack @5€/monat bringt uns auf ein quota von 50GB

**Comment by MG-5** [comment]
Mittlerweile verbrauchen wir nach einem Monat nur 0,23Gb an Bandbreite
